version: "2.4"
services:
  devshift.newsboardmanagement.api:
    container_name: devshift.newsboardmanagement.api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      TZ: Asia/Bangkok
    cpus: 1
    mem_limit: 1gb
    network_mode: bridge
    volumes:
      - ../secrets/secrets.json:/app/secrets.json
    #   - ../secrets/Certs/client-cert.pem:/app/Certs/client-cert.pem
    #   - ../secrets/Certs/client-key.pem:/app/Certs/client-key.pem
    #   - ../secrets/Certs/ap-southeast-1-bundle.pem:/app/Certs/ap-southeast-1-bundle.pem
    #   - ../secrets/Certs/nio.crt:/usr/local/share/ca-certificates/nio.crt
    image: markpunbu/devshift.newsboardmanagement.api:latest
    # logging:
    #   driver: fluentd
    #   options:
    #     tag: dotnet
    ports:
      - "32002:32002"
    restart: unless-stopped
    ulimits:
      core: 0
    extra_hosts:
      - "workstation01.devshift.local:192.22.1.102"
