version: "2.4"
services:
  devshift.newsboardmanagement.api:
    container_name: devshift.newsboardmanagement.api
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      TZ: Asia/Bangkok
    cpus: 1
    mem_limit: 1gb
    network_mode: bridge
    volumes:
      - ../secrets/secrets.json:/app/secrets.json
    image: markpunbu/devshift.newsboardmanagement.api:latest
    # logging:
    #   driver: fluentd
    #   options:
    #     tag: dotnet
    ports:
      - "32002:32002"
    restart: unless-stopped
    extra_hosts:
      - "workstation01.devshift.local:192.22.1.102"
